[package]
name = "grid_env"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.4"

[build-dependencies]
embed-resource = "2.2.0"