[package]
name = "grid_env"
version = "0.1.9"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.2"
rand = "0.8.5"
noise = "0.8.2"

[build-dependencies]
embed-resource = "2.2.0"